---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ${CLUSTER_NAME}
  region: ${AWS_DEFAULT_REGION}
  version: "1.21"
  tags:
    karpenter.sh/discovery: ${CLUSTER_NAME}
vpc:
  subnets:
    private:
      us-east-1b: { id: subnet-014533d6ce71b865e }
      us-east-1a: { id: subnet-04a9596cee2754df8 }
    public:
      us-east-1b: { id: subnet-04169f14f7ee86ab3 }
      us-east-1a: { id: subnet-0820b2d09794f06a9 }
managedNodeGroups:
  - instanceType: t2.medium
    amiFamily: AmazonLinux2
    name: ${CLUSTER_NAME}-ng
    desiredCapacity: 1
    privateNetworking: false
    minSize: 1
    maxSize: 10
iam:
  withOIDC: true